// <auto-generated />
namespace S00165311Week6Lab2.Migrations.ClubModelMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialiseClubs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialiseClubs));
        
        string IMigrationMetadata.Id
        {
            get { return "201711101145367_initialiseClubs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
